// Default module feature flags — all enabled for newly activated users.
// Mirrors the Organization entity's feature_flags defaults.
export const DEFAULT_FEATURE_FLAGS = {
  data_ingestion: true,
  investigations: true,
  alerts: true,
  case_management: true,
  sanctions_screening: true,
  network_explorer: true,
  ingestion_screening: true,
  entity_intelligence: true,
  autonomous_engine: true,
  analytics: true,
  collusion_detector: true,
  what_if_sandbox: true,
  insider_threat: true,
  crypto_audit: true,
  osint_scanner: true,
  vendor_verification: true,
  fx_stress_test: true,
  regulatory_horizon: true,
  reports_exports: true,
  risk_rules: true,
  daily_reports: true,
  hr_dashboard: true,
  activity_stream: true,
  relief_calendar: true,
  resource_calculator: true,
  integrations: true,
  audit_log: true,
  ai_chatbox: true,
  support: true,
  settings: true,
  raviqen_oversight: true,
  staff_ai_chatbox: false,
};