// Payroll export utilities — payslip PDFs, bank disbursement files, and audit reports
import jsPDF from "jspdf";

function downloadFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

// Generate a single-employee payslip PDF
export function generatePayslipPDF(record, employee, companyProfile) {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(companyProfile?.company_name || "RAVIQEN", pw / 2, 20, { align: "center" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  if (companyProfile?.address) doc.text(companyProfile.address, pw / 2, 26, { align: "center" });
  if (companyProfile?.contact_email) doc.text(companyProfile.contact_email, pw / 2, 31, { align: "center" });

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("PAYSLIP", pw / 2, 42, { align: "center" });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Pay Period: ${record.pay_period_month} ${record.pay_period_year}`, pw / 2, 48, { align: "center" });

  // Employee info
  let y = 60;
  doc.setFillColor(245, 245, 245);
  doc.rect(14, y - 5, pw - 28, 22, "F");
  doc.setFont("helvetica", "bold");
  doc.text("Employee Details", 18, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  doc.text(`Name: ${record.employee_name}`, 18, y);
  doc.text(`ID: ${record.employee_id}`, pw / 2, y);
  y += 5;
  doc.text(`Department: ${record.department}`, 18, y);
  doc.text(`Position: ${employee?.role_title || "—"}`, pw / 2, y);

  // Earnings section
  y += 14;
  doc.setFont("helvetica", "bold");
  doc.text("Earnings", 14, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  doc.text(`Base Salary (${record.days_worked}/${record.scheduled_days} days):`, 18, y);
  doc.text(`$${record.base_salary.toFixed(2)}`, pw - 18, y, { align: "right" });
  y += 5;
  doc.text(`Overtime (${record.overtime_hours} hrs @ 1.5x/2x):`, 18, y);
  doc.text(`$${record.overtime_pay.toFixed(2)}`, pw - 18, y, { align: "right" });
  y += 5;
  doc.setFillColor(230, 230, 230);
  doc.rect(14, y - 4, pw - 28, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.text(`Gross Pay:`, 18, y);
  doc.text(`$${record.gross_pay.toFixed(2)}`, pw - 18, y, { align: "right" });

  // Deductions section
  y += 12;
  doc.setFont("helvetica", "normal");
  doc.text("Deductions", 14, y);
  y += 6;
  doc.text(`Late Arrival (${record.late_count} instances):`, 18, y);
  doc.text(`-$${record.late_deduction.toFixed(2)}`, pw - 18, y, { align: "right" });
  y += 5;
  doc.text(`Unexcused Absence (${record.absent_days} days):`, 18, y);
  doc.text(`-$${record.absence_deduction.toFixed(2)}`, pw - 18, y, { align: "right" });
  y += 5;
  doc.setFillColor(230, 230, 230);
  doc.rect(14, y - 4, pw - 28, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.text(`Total Deductions:`, 18, y);
  doc.text(`-$${record.total_deductions.toFixed(2)}`, pw - 18, y, { align: "right" });

  // Net pay
  y += 14;
  doc.setFillColor(20, 20, 30);
  doc.rect(14, y - 5, pw - 28, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.text(`NET PAY: $${record.net_pay.toFixed(2)}`, pw / 2, y + 2, { align: "center" });
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);

  // Attendance summary
  y += 16;
  doc.setFont("helvetica", "bold");
  doc.text("Attendance Summary", 14, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  const a = record.attendance_summary || {};
  doc.text(`Present: ${a.present || 0}  |  Late: ${a.late || 0}  |  Absent: ${a.absent || 0}  |  Overtime Days: ${a.overtime || 0}`, 14, y);
  y += 5;
  const bv = record.biometric_verification || {};
  doc.text(`Biometric Verified: ${bv.biometric_verified || 0}  |  Manual Entry: ${bv.manual_entry || 0}  |  CSV Upload: ${bv.csv_upload || 0}`, 14, y);

  // Anomaly flags
  if (record.anomaly_flags && record.anomaly_flags.length > 0) {
    y += 8;
    doc.setTextColor(200, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text(`⚠ Risk Flags: ${record.anomaly_flags.join(", ")}`, 14, y);
    doc.setTextColor(0, 0, 0);
  }

  // Footer
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated by RAVIQEN on ${new Date().toLocaleDateString()}`, 14, 285);
  if (companyProfile?.contact_phone) doc.text(companyProfile.contact_phone, pw - 14, 285, { align: "right" });

  return doc;
}

export function downloadPayslipPDF(record, employee, companyProfile) {
  const doc = generatePayslipPDF(record, employee, companyProfile);
  doc.save(`payslip_${record.employee_id}_${record.pay_period_month}_${record.pay_period_year}.pdf`);
}

// Export bank disbursement CSV (NIBSS-compatible format)
export function exportBankDisbursementCSV(payrollRecords, employees) {
  const approved = payrollRecords.filter((r) => r.status === "approved" || r.status === "disbursed" || r.status === "draft");
  const headers = ["SN", "Account Number", "Account Name", "Bank Code", "Amount", "Narration", "Payment Reference"];

  const rows = approved.map((r, i) => {
    const emp = employees.find((e) => e.employee_id === r.employee_id);
    const bankDetails = emp?.bank_account_details || "";
    const acctMatch = bankDetails.match(/(\d{10,12})/);
    const accountNumber = acctMatch ? acctMatch[1] : "0000000000";
    return [
      i + 1,
      accountNumber,
      r.employee_name,
      "000000",
      r.net_pay.toFixed(2),
      `Salary ${r.pay_period_month} ${r.pay_period_year}`,
      `PAY-${r.employee_id}-${r.pay_period_month}${r.pay_period_year}`,
    ];
  });

  const csv = [headers, ...rows].map((r) => r.join(",")).join("\n");
  const period = `${payrollRecords[0]?.pay_period_month || "current"}_${payrollRecords[0]?.pay_period_year || ""}`;
  downloadFile(csv, `bank_disbursement_${period}.csv`, "text/csv");
}

// Export master payroll audit PDF
export function exportPayrollAuditPDF(payrollRecords, companyProfile) {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(companyProfile?.company_name || "RAVIQEN", pw / 2, 18, { align: "center" });
  doc.setFontSize(12);
  doc.text("Payroll Audit Report", pw / 2, 26, { align: "center" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const period = `${payrollRecords[0]?.pay_period_month || ""} ${payrollRecords[0]?.pay_period_year || ""}`;
  doc.text(`Period: ${period}`, pw / 2, 32, { align: "center" });
  doc.text(`Generated: ${new Date().toLocaleString()}`, pw / 2, 37, { align: "center" });

  // Summary
  const totalGross = payrollRecords.reduce((s, r) => s + r.gross_pay, 0);
  const totalNet = payrollRecords.reduce((s, r) => s + r.net_pay, 0);
  const totalOT = payrollRecords.reduce((s, r) => s + r.overtime_pay, 0);
  const totalDed = payrollRecords.reduce((s, r) => s + r.total_deductions, 0);
  const flagged = payrollRecords.filter((r) => r.anomaly_flags.length > 0).length;

  let y = 48;
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  doc.text(`Total Employees: ${payrollRecords.length}`, 14, y);
  doc.text(`Total Gross: $${totalGross.toFixed(2)}`, pw / 2, y);
  y += 5;
  doc.text(`Total Overtime: $${totalOT.toFixed(2)}`, 14, y);
  doc.text(`Total Deductions: $${totalDed.toFixed(2)}`, pw / 2, y);
  y += 5;
  doc.text(`Total Net Pay: $${totalNet.toFixed(2)}`, 14, y);
  doc.text(`Flagged Records: ${flagged}`, pw / 2, y);

  // Table header
  y += 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.text("Emp ID", 14, y);
  doc.text("Name", 36, y);
  doc.text("Dept", 82, y);
  doc.text("Days", 105, y);
  doc.text("OT Hrs", 120, y);
  doc.text("Gross", 138, y);
  doc.text("Deduct", 160, y);
  doc.text("Net", 180, y);
  doc.text("Risk", 200, y);

  doc.setDrawColor(200, 200, 200);
  doc.line(14, y + 1, pw - 14, y + 1);

  doc.setFont("helvetica", "normal");
  y += 6;

  for (const r of payrollRecords) {
    if (y > 272) {
      doc.addPage();
      y = 20;
    }
    doc.text(String(r.employee_id || "").substring(0, 12), 14, y);
    doc.text(String(r.employee_name || "").substring(0, 20), 36, y);
    doc.text(String(r.department || "").substring(0, 8), 82, y);
    doc.text(String(r.days_worked), 105, y);
    doc.text(String(r.overtime_hours), 120, y);
    doc.text(`$${r.gross_pay.toFixed(0)}`, 138, y);
    doc.text(`$${r.total_deductions.toFixed(0)}`, 160, y);
    doc.text(`$${r.net_pay.toFixed(0)}`, 180, y);
    doc.text(r.anomaly_flags.length > 0 ? `! ${r.anomaly_flags.length}` : "OK", 200, y);
    y += 5;
  }

  // Footer
  doc.setFontSize(8);
  doc.text(`RAVIQEN Payroll Audit — ${new Date().toLocaleDateString()}`, 14, 288);

  doc.save(`payroll_audit_${period.replace(/\s+/g, "_")}.pdf`);
}

// Export payroll audit CSV
export function exportPayrollAuditCSV(payrollRecords) {
  const headers = [
    "Employee ID", "Name", "Department", "Days Worked", "Regular Hours", "OT Hours",
    "Base Salary", "OT Pay", "Late Deduction", "Absence Deduction", "Gross Pay",
    "Total Deductions", "Net Pay", "Risk Level", "Anomaly Flags", "Biometric Verified", "Manual Entry",
  ];

  const rows = payrollRecords.map((r) => [
    r.employee_id,
    r.employee_name,
    r.department,
    r.days_worked,
    r.regular_hours,
    r.overtime_hours,
    r.base_salary.toFixed(2),
    r.overtime_pay.toFixed(2),
    r.late_deduction.toFixed(2),
    r.absence_deduction.toFixed(2),
    r.gross_pay.toFixed(2),
    r.total_deductions.toFixed(2),
    r.net_pay.toFixed(2),
    r.risk_level,
    r.anomaly_flags.join("; "),
    r.biometric_verification?.biometric_verified || 0,
    r.biometric_verification?.manual_entry || 0,
  ]);

  const csv = [headers, ...rows].map((r) => r.map((c) => `"${c}"`).join(",")).join("\n");
  const period = `${payrollRecords[0]?.pay_period_month || "current"}_${payrollRecords[0]?.pay_period_year || ""}`;
  downloadFile(csv, `payroll_audit_${period}.csv`, "text/csv");
}